### ISSUE TITLE
Doc: http client configuration example not working

### ISSUE THREAD

**Issue by ArthurD1** [msqd/harp#553]
The full example in the [HTTP client doc](https://docs.harp-proxy.net/en/0.7/apps/http_client/index.html) is not working. Copy pasting it will lead to type errors such as:
`got an unexpected keyword argument '@type'`

**Comment by hartym** [comment]
This should be picked up by the CI, as a part of the doc fix. There are already tests that parse example files, that may be as simple as converting it to an included yaml files picked up by the existing tests.
