### ISSUE TITLE
As a cookiecutter template user, I want not to be able to generate invalid python package names. The directory name should use hyphens, while the python package name should use underscores, and invalid characters should be stripped out from both. We can use hidden variables (cookiecutter double underscore) to avoid prompting

### ISSUE THREAD

**Issue by hartym** [msqd/harp#565]
**Epic:** [Developper Experience](https://trello.com/c/ZvrqhvT9)

Enhancing the `harp create project` user experience.

**Comment by Lenormju** [comment]
When using `té&#ç^è$=}` as project name, the directory created is called `te-c-e`, and the package is called `te_c_e` in the `pyproject.toml`. [`cookiecutter`'s `slugify`](https://github.com/msqd/harp/blob/85904bb994e692d862db7680bc5308476a4a4801/harp/commandline/cookiecutters/project/cookiecutter.json#L4-L5) seems to do the job already.
Looks good to me, I would consider closing the issue.

**Comment by hartym** [comment]
Indeed.
